// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CategorySubscriptionController from "./category_subscription_controller"
application.register("category-subscription", CategorySubscriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RedirectionController from "./redirection_controller"
application.register("redirection", RedirectionController)
